apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: haowg7wum-python 
  janus-idp.io/tekton: haowg7wum-python
  backstage.io/kubernetes-id: haowg7wum-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: haowg7wum-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml