apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: haowg7wum-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: haowg7wum-python 
  name: haowg7wum-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: haowg7wum-python 
